version: "3"

services:
  postgres:
    container_name: escrowx-postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=escrowx_db
      - POSTGRES_HOST=localhost
    ports:
      - 5457:5432
