# Generated by Django 5.0.4 on 2024-04-17 15:46

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("item_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.CharField(),
        ),
    ]
