# Generated by Django 5.0.4 on 2024-04-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_control', '0002_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
