# Generated by Django 5.0.4 on 2024-04-17 13:52

import django.db.models.deletion  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_control", "0001_initial"),
        ("transaction_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="item_control.item",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
