# Generated by Django 5.0.4 on 2024-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_control', '0002_alter_transaction_item_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
